apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: devopsmsb123.azurecr.io/devopsproject:latest
        ports:
        - containerPort: 3000           # Must match app PORT
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGODB_URI
        - name: PORT
          value: "3000"
